security:
    providers:
        user_provider:
            entity:
                class: App\Entity\User
                property: email

    encoders:
        App\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            provider: user_provider
            form_login:
                post_only: true
                login_path: index
                check_path: index
                use_referer: false
                remember_me: false
                username_parameter: email
                default_target_path: /
                password_parameter: password
                require_previous_session: false
                always_use_default_target_path: false
            logout:
                target: /
                path: /logout
                success_handler: ~
                invalidate_session: true

    access_control:
        - { path: ^/home, roles: ROLE_USER }
